config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'questions' => 'static_pages#questions'
  get 'career' => 'static_pages#career'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'signup' => 'users#new'
  resources :users, except: [:show, :destroy]

  resources :shoppers, only: [] do
    resources :milktea_orderables, only: [:create]
    resources :orderables, only: [:create]
    resources :orders, only: [:create, :index]
    get 'cart' => 'orderables#index'
    get 'checkout' => 'orders#new'
  end

  resources :admins, only: [] do
    resources :orders, only: [:index]
  end

  resources :orderables, only: [:update, :destroy]
  resources :orders, only: [:show, :update]
  
  resources :milkteas, only: [] do
    resources :milktea_orderables, only: [:new]
  end
  
  resources :milktea_orderables, only: [:edit, :update]

  get 'menu' => 'recipes#index'
  resources :recipes, only: [:create, :show, :edit, :update] do 
    get 'manage', on: :collection
  end

  resources :dish_categories, only: [:create, :edit, :update]
  resources :milktea_addons, only: [:create, :edit, :update]

  resources :stores
  resources :pickup_locations, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :locations_times, only: [:create]  
    resources :orders, only: [:new, :create]
  end

  resources :pickup_times, only: [:create, :edit, :update, :destroy]

  get 'schedule' => 'locations_times#schedule'
  resources :locations_times, only: [:destroy] do
    resources :orders, only: [:new, :create]
  end

end

app/models/store.rb
class Store < ActiveRecord::Base
	include StorePresentor
	include Propagatable
	has_many :providers
	has_many :recipes
	
	validates :name, presence: true, length: { maximum: 50 }
	validates :phone, presence: true, length: { maximum: 20 }
	validates :owner, presence: true, length: { maximum: 255 }
	validates :address, presence: true, length: { maximum: 255 }
	# validates :lat, presence: true
	# validates :long, presence: true

	#optional attributes
	validates :email, length: { maximum: 255 }
	validates :website, length: { maximum: 255 }
	
	before_create :default_lat_long #placeholder for lat and long
	after_update :lazy_propagate_state_change
	
	def disable
		update_attribute(:active, false)
	end
	
	private

		def default_lat_long
			self.lat = 0 if lat.nil?
			self.long = 0 if long.nil?
		end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	before_action :logged_in_user
	before_action :valid_store, only: [:show, :edit, :update]

	after_action :verify_authorized

	def index
		authorize Store
		@stores = Store.all
	end

	def new
		authorize Store
		@store = Store.new
	end

	def create
		authorize Store
		@store = Store.new store_params
		@store.save ? redirect_and_flash(store_url(@store), :success, "Store created") : render('new')
	end

	def show
		authorize @store
	end	
	
	def edit
		authorize @store
	end
	
	def update
		authorize @store
		if @store.update_attributes(store_params)
			redirect_and_flash(store_url(@store), :success, "Store updated")
		else
			render 'edit'
		end
	end
	
	private 

		def store_params
			params.require(:store).permit(policy(Store).permitted_attributes)
		end

		def valid_store
			@store = Store.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			redirect_and_flash(menu_url, :error, "Invalid store")
		end	

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for @store, html: { class: ['ui', 'form'] } do |f| %>
	<%= render 'shared/error_msgs', object: f.object %>

	<div class="field">
		<%= f.label :name, "Store" %>
		<%= icon_input_wrapper(f, :name, :building, { placeholder: "Name of new store" }) %>
	</div>

	<div class="field">
		<%= f.label :phone %>
		<%= icon_input_wrapper(f, :phone, :phone, { placeholder: "Primary contact number" }) %>
	</div>

	<div class="field">
		<%= f.label :owner %>
		<%= icon_input_wrapper(f, :owner, :user, { placeholder: "Name of owner or primary contact" }) %>
	</div>

	<div class="field">
		<%= f.label :address %>
		<%= icon_input_wrapper(f, :address, :marker, { placeholder: "Adderss of new store" }) %>
	</div>

	<div class="field">
		<%= f.label :email %>
		<%= icon_input_wrapper(f, :email, :mail, { placeholder: "Primary contact email (optional)" }) %>
	</div>

	<div class="field">
		<%= f.label :website %>
		<%= icon_input_wrapper(f, :website, :laptop, { placeholder: "Store website (optional)" }) %>
	</div>

	<div class="field">
		<%= f.submit yield(:button_text), class: "ui inverted #{yield(:button_color)} button" %>
	</div>
<% end %>

app/views/stores/_store_info_card.html.erb
<div class="ui fluid card">
	<div class="content">
		<div class="header center aligned">
			<span class="storeInfoTitle">Store Info</span>
			<p class="ui <%= @store.active? ? 'green' : 'red' %> tiny label storeLabel">
				<%= @store.present_active.capitalize %>
			</p>
			<%= link_to "Edit", edit_store_url(@store), class: "ui teal tiny label storeLabel" %>
		</div>

		<div class="description">
			<div class="row">
				<div class="ui container grid">

					<div class="eight wide column">
						<p>Primary contact: <span class="storeInfo"><%= @store.owner %></span></p>
						<p>Primary contact Number: <span class="storeInfo"><%= @store.phone %></span></p>
						<p>Primary contact Email: <span class="storeInfo"><%= @store.email || "N/A" %></span></p>
					</div>

					<div class="eight wide column">
						<p>Store name: <span class="storeInfo"><%= @store.name.capitalize %></span>
						<p>Store website: <span class="storeInfo"><%= @store.website.nil? ? "N/A" : link_to("Click here", @store.website, target: "_blank") %></span></p>
						<p>Store location: <span class="storeInfo"><%= @store.address %></span></p>
					</div>

				</div>
			</div>
		</div>

	</div>
</div>

app/views/stores/_store_provider_info.html.erb
<% @store.providers.each do |provider| %>
	<span class="storeProviderInfo">
		<%= link_to provider.name.capitalize, "#", class: ("success" if provider.chief_liaison?) %>
	</span>
<% end %>

app/views/stores/_store_providers_card.html.erb
<div class="ui fluid card">
	<div class="content">
		<div class="header center aligned">
			<span class="storeInfoTitle">Store Providers</span>
			<%= link_to "Add Provider", "#", class: "ui teal tiny label storeLabel" %>
		</div>

		<div class="description">
			<%= @store.providers.empty? ? "This store has no provider" : render("stores/store_provider_info") %>
		</div>	
	</div>
</div>

app/views/stores/edit.html.erb
<% provide(:title, "Edit Store") %>
<% provide(:button_text, "Update Store") %>
<% provide(:button_color, "red") %>

<div class="row">
	<div class="ui breadcrumb">
	  <%= link_to "Store Management", stores_url, class: "section" %>
	  <i class="right angle icon divider"></i>
	  <%= link_to @store.name.capitalize, store_url(@store), class: "section" %>
	  <i class="right angle icon divider"></i>
	  <div class="active section">Edit</div>
	</div>
</div>

<div class="row">
	<div class="ui container grid">
		<div class="row">
      <div class="column">
        <%= render 'stores/form' %>
        <%= render 'shared/toggle_active_button', object: @store, name: "Store" %>
        <small>**Extreme Caution: Disabling store will disable all associated menu items!</small>
      </div>
		</div>
	</div>
</div>

app/views/stores/index.html.erb
<% provide(:title, "Store Management") %>
<%= render 'shared/admin_nav' %>

<div class="centered row">
	<div class="categoryTitle">Store Management</div>
</div>

<div class="row">
  <% @stores.each do |store| %>
    <div class="four wide column">
      
      <div class="ui fluid card">
        <div class="content">
          <div class="header"><%= link_to store.name.capitalize, store_url(store) %></div>
          <div class="description">
            Pending...(this is a placeholder for google map static image)
          </div>
        </div>
        
        <div class="extra content">
          <div class="ui label <%= store.active? ? 'green' : 'red' %> tiny"><%= store.present_active.capitalize %></div>
        </div>
        
      </div>
      
    </div>     
  <% end %> 
</div>

app/views/stores/new.html.erb
<% provide(:title, "New Store") %>
<% provide(:button_text, "Create New Store") %>
<% provide(:button_color, "blue") %>

<div class="row">
	<div class="ui breadcrumb">
	  <%= link_to "Store Management", stores_url, class: "section" %>
	  <i class="right angle icon divider"></i>
	  <div class="active section">New Store</div>
	</div>
</div>

<div class="row">
	<div class="ui container grid">
		<div class="row">
			<div class="column">
				<%= render 'stores/form' %>
			</div>
		</div>
	</div>
</div>

app/views/stores/show.html.erb
<% provide(:title, @store.name) %>

<div class="row">
	<div class="ui breadcrumb">
	  <%= link_to "Store Management", stores_url, class: "section" %>
	  <i class="right angle icon divider"></i>
	  <div class="active section"><%= @store.name.capitalize %></div>
	</div>
</div>

<div class="row">
	<div class="ui container grid">
		<div class="row">
			<div class="eight wide column">
				<%= render 'stores/store_info_card' %>
			</div>

			<div class="eight wide column">
				<%= render 'stores/store_providers_card' %>
			</div>
		</div>

		<div class="row">
			<div class="column">
				<div class="ui fluid card">
					<div class="content center aligned">
						<div class="header">Store Stats</div>
						<div class="description">
							Coming...
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>