config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'questions' => 'static_pages#questions'
  get 'career' => 'static_pages#career'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'signup' => 'users#new'
  resources :users, except: [:show, :destroy]

  resources :shoppers, only: [] do
    resources :milktea_orderables, only: [:create]
    resources :orderables, only: [:create]
    resources :orders, only: [:create, :index]
    get 'cart' => 'orderables#index'
    get 'checkout' => 'orders#new'
  end

  resources :admins, only: [] do
    resources :orders, only: [:index]
  end

  resources :orderables, only: [:update, :destroy]
  resources :orders, only: [:show, :update]
  
  resources :milkteas, only: [] do
    resources :milktea_orderables, only: [:new]
  end
  
  resources :milktea_orderables, only: [:edit, :update]

  get 'menu' => 'recipes#index'
  resources :recipes, only: [:create, :show, :edit, :update] do 
    get 'manage', on: :collection
  end

  resources :dish_categories, only: [:create, :edit, :update]
  resources :milktea_addons, only: [:create, :edit, :update]

  resources :stores
  resources :pickup_locations, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :locations_times, only: [:create]  
    resources :orders, only: [:new, :create]
  end

  resources :pickup_times, only: [:create, :edit, :update, :destroy]

  get 'schedule' => 'locations_times#schedule'
  resources :locations_times, only: [:destroy] do
    resources :orders, only: [:new, :create]
  end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	include Propagatable
	scope :active, -> { where(active: true) }

	belongs_to :store
	
	validates :name, presence: true, length: { maximum: 50 }
	validates :description, presence: true, length: { maximum: 255 }
	validates :image, presence: true
	validates :price, presence: true, numericality: { greater_than: 0 }
	validates :type, presence: true, inclusion: { in: ["Dish", "Milktea"], message: "%{value} is not a valid type" }
	validates :store, presence: true
	
	mount_uploader :image, PictureUploader
	validate :picture_size
	validate :immutable_type
	
	after_update :propagate_state_change
	after_update :propagate_price_change
	
	def disable
		update_attribute(:active, false)
	end
	
	def activate
		update_attribute(:active, true)
	end
	
	def unit_price
		price
	end

	private

		def immutable_type
			 errors.add(:type, "cannot be changed" ) if type_changed? && persisted?			
		end

		def picture_size
			errors.add(:image, "should be less than 1MB") if image.size > 1.megabytes
		end

end

app/models/recipes/dish.rb
class Dish < Recipe
	belongs_to :dish_category
	has_many :orderables, as: :buyable

	validates :dish_category, presence: true

	#Caution! This hack may cause unexpected behaviors.
	#I'm unsure if model_name is used by Rails internal for other purposes. 
	#However, I'll go with it for now for its brevity.
	def self.model_name
		Recipe.model_name
	end

end

app/models/recipes/milktea.rb
class Milktea < Recipe
	has_many :milktea_orderables
	validates :dish_category_id, absence: true

	#Caution! This hack may cause unexpected behaviors.
	#I'm unsure if model_name is used by Rails internal for other purposes. 
	#However, I'll go with it for now for its brevity.
	def self.model_name
		Recipe.model_name
	end
		
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :logged_in_user, except: [:show, :index]
	before_action :valid_recipe, only: [:show, :edit, :update]

	after_action :verify_authorized, except: [:show, :index]
	
	def manage
		authorize Recipe
		load_resources
		@recipe = Recipe.new
		render 'shared/manage'
	end

	def index
		@dish_categories = DishCategory.all
		@milkteas = Milktea.active
	end

	def create
		authorize Recipe
		load_resources
		@recipe = Recipe.new(recipe_params)
		@recipe.save ? redirect_and_flash(manage_recipes_url, :success, "Item created") : render('shared/manage')
	end

	def edit
		authorize Recipe
	end

	def update
		authorize Recipe
		if params[:recipe][:active]
			params[:recipe][:active] == "0" ? @recipe.disable : @recipe.activate
			redirect_and_flash(manage_recipes_url, :success, "Item updated")
		else #recipe now propagates status change via after_update callback
			@recipe.update_attributes(recipe_params) ? redirect_and_flash(manage_recipes_url, :success, "Item updated") : render('edit')
		end
	end

	def show
	end 

	private 

	def recipe_params
		params.require(:recipe).permit(:name, :description, :image, :price, :store_id, :type, :dish_category_id)
	end
	
	def valid_recipe
		@recipe = Recipe.find(params[:id])
	rescue ActiveRecord::RecordNotFound
		redirect_and_flash(menu_url, :error, "Invalid item")
	end
	
	def load_resources
		@dish_category = DishCategory.new
		@milktea_addon = MilkteaAddon.new
		@dish_categories = DishCategory.all
		@addons = MilkteaAddon.all
	end
end

app/views/recipes/_form.html.erb
<%= form_for @recipe, html: { multipart: true, class: ["ui", "form"], id: "editRecipeForm"} do |f| %>
	<%= render 'shared/error_msgs', object: f.object %>
	<div class="field">
		<%= f.label :name, yield(:label_name) %>
		<%= icon_input_wrapper(f, :name, :spoon, { placeholder: "New menu item name" }) %>
	</div>

	<div class="field">
		<%= f.label :price %>
		<%= icon_input_wrapper(f, :price, :dollar, { placeholder: "New menu item price, number only!" }) %>
	</div>

	<div class="field">
		<%= f.label :store %>
		<%= f.collection_select(:store_id, Store.where("active =? ", true), :id, :name, { prompt: "Select Store:" }, { class: "ui dropdown" }) %>
	</div>

	<% unless @recipe.type %>
			<div class="field">
				<%= f.label :type %>
				<%= f.select(:type, [['Dish', 'Dish'], ['Milk Tea', 'Milktea']], { prompt: "Select Item Type:" }, { class: "ui dropdown" }) %>
			</div>
	<% end %>

	<div class="field" id="<%= 'newRecipeDishCategory' unless @recipe.type == 'Dish' %>">
		<%= f.label :dish_category_id %>
		<%= f.collection_select(:dish_category_id, DishCategory.where("active = ?", true), :id, :name, { prompt: "Select Category" }, { class: "ui dropdown" }) %>
	</div>
	
	<div class="field">
		<%= f.label :image %>
		<%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png'%>
	</div>


	<div class="field">
		<%= f.label :description %>
		<%= f.text_area(:description, rows: 3, placeholder: "Description comes in here...") %>
	</div>

	<div class="field">
		<%= f.submit yield(:button_text), class: "ui inverted #{yield(:button_class)} button" %>
	</div>

<% end %>

app/views/recipes/_new_addon.html.erb
<div class="column">
	<h4 class="ui horizontal divider header">
	  <i class="tag icon"></i>
	  New Milk Tea Add-on
	</h4>
	<%= form_for @milktea_addon, html: { class: ["ui", "form"], id: "newAddonForm"} do |f| %>
		<div class="field">
			<%= f.label :name %>
			<%= icon_input_wrapper(f, :name, :write, { placeholder: "Bubble" }) %>
		</div>

		<div class="field">
			<%= f.label :price %>
			<%= icon_input_wrapper(f, :price, :dollar, { placeholder: "Please enter numeric values only!" }) %>
		</div>

		<%= f.submit "Create New Add-on", class: "ui inverted blue button" %>
	<% end %>
</div>

app/views/recipes/_new_dish_category.html.erb
<div class="column">
	<h4 class="ui horizontal divider header">
	  <i class="tag icon"></i>
	  New Dish Category
	</h4>
	<%= form_for @dish_category, html: { class: ["ui", "form"], id: "newDishCategoryForm" } do |f| %>
		
		<div class="field">
			<%= f.label :name %>
			<%= icon_input_wrapper(f, :name, :write, { placeholder: "GGGGGDragon style salad variations" }) %>
		</div>

		<div class="field">
			<%= f.label :image %>
			<%= icon_input_wrapper(f, :image, "file outline", { placeholder: "upload image" }) %>
		</div>

		<div class="field">
			<%= f.label :description %>
			<%= f.text_area(:description, rows: 5, placeholder: "Category description comes in here...") %>
		</div>

		<%= f.submit "Create New Category", class: "ui inverted blue button" %>
	<% end %>
</div>

app/views/recipes/_new_recipe.html.erb
<% provide(:button_text, "Create New Menu Item") %>
<% provide(:label_name, "New Menu Item") %>
<% provide(:button_class, "blue") %>
<div class="ui fluid card" id="newRecipeCard">
	<div class="content">
		<%= render 'recipes/form' %>
	</div>
</div>

app/views/recipes/_recipe.html.erb
<div class="row">
	<%= recipe.name.upcase %> <%= recipe.price %>
</div>
<div class="row menuDescriptionRow">
	<em><%= recipe.description %></em>
</div>
<div class="row menuButtonRow">
	<%= link_to semantic_icon("list circular"), recipe_path(recipe), class: "menuButton" %>
	<% if recipe.is_a? Milktea %>
		<%= link_to semantic_icon("add to cart circular"), (logged_in? ? new_milktea_milktea_orderable_path(recipe) : login_path), class: "menuButton" %>
	<% else %>
		<% if logged_in? %>
			<%= link_to semantic_icon("add to cart circular"), shopper_orderables_path(shopper_id: current_user.role_id, type: "dish", buyable_id: recipe.id), class: "menuButton", method: :post %>
		<% else %>
			<%= link_to semantic_icon("add to cart circular"), login_path, class: "menuButton" %>
		<% end %>
	<% end %>
</div>

app/views/recipes/_toggle_active_button.html.erb
<% if @recipe.active %>
	<div class="ui segment">
	  <div class="field">
	    <div class="ui toggle checkbox">
	      <input type="checkbox" name="delete_confirm" id="delete_confirm" tabindex="0" class="hidden">
	      <label>Unlock Disable Button</label>
	    </div>
	  </div>
	</div>

	<%= form_for @recipe, html: { class: ["ui", "form"] } do |f| %>
		<%= f.hidden_field :active, value: 0 %> 
		<%= f.submit "Disable Item", class:"ui disabled inverted red button deleteButton" %>
	<% end %>

<% else %>

	<%= form_for @recipe, html: { class: ["ui", "form", "toggleActiveForm"] } do |f| %>
		<%= f.hidden_field :active, value: 1 %> 
		<%= f.submit "Activate Item", class:"ui inverted orange button" %>
	<% end %>

<% end %>

app/views/recipes/edit.html.erb
<% provide(:title, "Edit Item") %>
<% provide(:button_text, "Adjust Item Info") %>
<% provide(:label_name, "Name") %>
<% provide(:button_class, "red") %>
<div class="row">
	<div class="ui breadcrumb">
	  <%= link_to "Menu Management", manage_recipes_url, class: "section" %>
	  <i class="right angle icon divider"></i>
	  <div class="active section">Edit Recipe</div>
	</div>
</div>

<div class="row">
	<div class="ui container grid">
		<div class="row">
			<div class="six wide middle aligned column">
				<%= image_tag @recipe.image.url.to_s, class:"ui centered image" if @recipe.image? %>
			</div>
			<div class="ten wide column">
					<%= render 'form' %>
					<small>**Extreme Caution: changing item information can affect existing orders!</small>
					<%= render 'shared/toggle_active_button', object: @recipe, name: "Item" %>
			</div>
		</div>
	</div>
</div>

app/views/recipes/index.html.erb
<% provide(:title, "Menu") %>

<div class="centered row">
	<div class="twelve wide column">
		<div class="ui fluid card">
			<div class="content">
				<div class="center aligned categoryTitle">TAIJI MILKTEA</div>
				<div class="description">
					<div class="ui container grid">

						<div class="two column stackable row">
							<% @milkteas.each do |milktea| %>
								<div class="center aligned column">
									<%= render 'recipe', recipe: milktea %>
								</div>
							<% end %>
						</div>

					</div>
				</div>
			</div>
		</div>


		<% @dish_categories.each do |dish_category| %>
			<div class="ui fluid card">
				<div class="content">
					<div class="center aligned categoryTitle"><%= dish_category.name.upcase %></div>
					<div class="description">
						<div class="ui container grid">
							<div class="two column stackable row">
								<% dish_category.dishes.where("active = ?", true).each do |recipe| %>
									<div class="center aligned column">
										<%= render 'recipe', recipe: recipe %>
									</div>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/recipes/manage.html.erb
<% provide(:title, "Recipe Management") %>
<%= render 'shared/admin_nav' %>

<h1 class="ui header title">Menu Management</h1>

<h4 class="ui horizontal divider header">
  <i class="tag icon"></i>
  New Menu Item
</h4>
<div class="row" id="newRecipeRow">
	<%= render 'new_recipe' %>
</div>

<div class="row">
	<div class="ui two column grid">
		<div class="row">
		<%= render 'new_dish_category' %>
		<%= render 'new_addon' %>
		</div>
	</div>
</div>

<div class="row">
	<h4 class="ui horizontal divider header">
	  <i class="cubes icon"></i>
	  All Products
	</h4>
</div>

app/views/recipes/show.html.erb
<% provide(:title, "Menu Item") %>

<div class="row">
	<div class="ui grid">

		<div class="six wide column">
			<%= image_tag @recipe.image.url.to_s, class:"ui centered image" if @recipe.image? %>
		</div>
		<div class="ten wide column">
			<h2 class="ui title header"><%= @recipe.name %></h2>
			<% unless @recipe.active %><p class="error">THIS ITEM IS NO LONGER AVAILABLE</p><% end %>
			<p>$ <%= @recipe.price %></p>
			<p><%= @recipe.description %></p>
		</div>

	</div>
</div>