config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'questions' => 'static_pages#questions'
  get 'career' => 'static_pages#career'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'signup' => 'users#new'
  resources :users, except: [:show, :destroy]

  resources :shoppers, only: [] do
    resources :milktea_orderables, only: [:create]
    resources :orderables, only: [:create]
    resources :orders, only: [:create, :index]
    get 'cart' => 'orderables#index'
    get 'checkout' => 'orders#new'
  end

  resources :admins, only: [] do
    resources :orders, only: [:index]
  end

  resources :orderables, only: [:update, :destroy]
  resources :orders, only: [:show, :update]
  
  resources :milkteas, only: [] do
    resources :milktea_orderables, only: [:new]
  end
  
  resources :milktea_orderables, only: [:edit, :update]

  get 'menu' => 'recipes#index'
  resources :recipes, only: [:create, :show, :edit, :update] do 
    get 'manage', on: :collection
  end

  resources :dish_categories, only: [:create, :edit, :update]
  resources :milktea_addons, only: [:create, :edit, :update]

  resources :stores
  resources :pickup_locations, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :locations_times, only: [:create]  
    resources :orders, only: [:new, :create]
  end

  resources :pickup_times, only: [:create, :edit, :update, :destroy]

  get 'schedule' => 'locations_times#schedule'
  resources :locations_times, only: [:destroy] do
    resources :orders, only: [:new, :create]
  end

end

app/views/shared/_admin_nav.html.erb
<div class="row">
	<div class="ui teal stackable five item menu">
		<%= nav_link("Orders", admin_orders_url(current_user.role)) %>
		<%= nav_link("Menu", manage_recipes_path) %>
		<%= nav_link("Delivery", pickup_locations_path) %>
		<%= nav_link("Stores", stores_path) %>
		<%= nav_link("Users", users_path) %>
	</div>
</div>

app/views/shared/_error_msgs.html.erb
<% if object.errors.any? %>
	<div class="ui error message" style="display:block;">
		<i class="close icon"></i>
		<div class="header">
			This form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul class="list">
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_toggle_active_button.html.erb
<% if object.active %>
	<div class="ui segment">
	  <div class="field">
	    <div class="ui toggle checkbox">
	      <input type="checkbox" name="delete_confirm" id="delete_confirm" tabindex="0" class="hidden">
	      <label>Unlock Disable Button</label>
	    </div>
	  </div>
	</div>

	<%= form_for object, html: { class: ["ui", "form"] } do |f| %>
		<%= f.hidden_field :active, value: 0 %> 
		<%= f.submit "Disable #{name}", class:"ui disabled inverted red button deleteButton" %>
	<% end %>

<% else %>

	<%= form_for object, html: { class: ["ui", "form", "toggleActiveForm"] } do |f| %>
		<%= f.hidden_field :active, value: 1 %> 
		<%= f.submit "Activate #{name}", class:"ui inverted orange button" %>
	<% end %>

<% end %>

app/views/shared/_user_nav.html.erb
<div class="row">
	<div class="ui teal stackable <%= current_user.admin? ? "two" : "three" %> item menu">
		<% unless current_user.admin? %>
			<%= nav_link("Orders", shopper_orders_url(current_user.role)) %>
		<% end %>
		<%= nav_link("Messages", "#") %>
		<%= nav_link("Edit Profile", edit_user_url(current_user)) %>
	</div>
</div>

app/views/shared/manage.html.erb
<% provide(:title, "Menu Management") %>
<%= render 'shared/admin_nav' %>
<div class="centered row">
	<div class="categoryTitle">Menu Management</div>
</div>


<div class="stackable row">
	
	<div class="five wide column">
		<div class="row">
			<div class="column">
				<%= render 'recipes/new_recipe' %>
			</div>
		</div>
		
		<div class="row">
			<div class="column">
				<%= render 'dish_categories/new_dish_category' %>
				<%= render 'milktea_addons/new_addon' %>
			</div>
		</div>
	</div>
	
	
	<div class="eleven wide column">
		<div class="row">
			<div class="ui container grid">
				<div class="stackable row">
					<% Milktea.all.each do |milktea| %>
						<div class="four wide column recipeManageIndexColumn">
							<div class="ui centered card">
								<div class="image">
									<%= link_to(image_tag(milktea.image.url, class:"ui image"), edit_recipe_url(milktea)) %>
								</div>
								<div class="content">
									<div class="header"><%= milktea.name %></div>
									<div class="meta">
										<a>Taichi Milktea</a>
									</div>
									<div class="description">
										<%= milktea.description %>
									</div>
								</div>
								<div class="extra content">
									<span class="left floated">
										<i class="dollar icon"></i>
										<%= milktea.price %>
									</span>
									<% if milktea.active %>
										<span class="right floated success">
											<i class="checkmark icon"></i>ACTIVE
										</span>
									<% else %>
										<span class="right floated error">
											<i class="remove icon"></i>INACTIVE
										</span>
									<% end %>
								</div>
							</div>
						</div>	
					<% end %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="ui container grid">
				<div class="stackable row">
					<%= render @dish_categories %>
				</div>
			</div>
		</div>
	</div>
	



	
</div>