config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'questions' => 'static_pages#questions'
  get 'career' => 'static_pages#career'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'signup' => 'users#new'
  resources :users, except: [:show, :destroy]

  resources :shoppers, only: [] do
    resources :milktea_orderables, only: [:create]
    resources :orderables, only: [:create]
    resources :orders, only: [:create, :index]
    get 'cart' => 'orderables#index'
    get 'checkout' => 'orders#new'
  end

  resources :admins, only: [] do
    resources :orders, only: [:index]
  end

  resources :orderables, only: [:update, :destroy]
  resources :orders, only: [:show, :update]
  
  resources :milkteas, only: [] do
    resources :milktea_orderables, only: [:new]
  end
  
  resources :milktea_orderables, only: [:edit, :update]

  get 'menu' => 'recipes#index'
  resources :recipes, only: [:create, :show, :edit, :update] do 
    get 'manage', on: :collection
  end

  resources :dish_categories, only: [:create, :edit, :update]
  resources :milktea_addons, only: [:create, :edit, :update]

  resources :stores
  resources :pickup_locations, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :locations_times, only: [:create]  
    resources :orders, only: [:new, :create]
  end

  resources :pickup_times, only: [:create, :edit, :update, :destroy]

  get 'schedule' => 'locations_times#schedule'
  resources :locations_times, only: [:destroy] do
    resources :orders, only: [:new, :create]
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
	include OrderPresentor

	belongs_to :shopper
	belongs_to :driver
	has_many :orderables, as: :ownable, dependent: :destroy

	enum satisfaction: %i(unrated worst bad indifferent good best)
	enum issue_status: %i(no_feedback feedback_created feedback_resolved)
	enum payment_status: %i(unpaid paid refunded)
	enum payment_method: %i(online cash)
	enum fulfillment_status: %i(received confirmed denied in_transit arrived delivered cancelled)
	#raise ArgumentError when value passed in is string or not included in the hash

	validates :total, presence: true, numericality: { greater_than: 0 }
	validates :recipient_name, presence: true, length: { maximum: 50 }
	validates :recipient_phone, presence: true, length: { maximum: 60 }
	validates :recipient_wechat, length: { maximum: 50 }
	validates :delivery_location, presence: true
	validates :delivery_time, presence: true
	validates :shopper, presence: true
	validates :issue, length: { maximum: 255 }
	validates :solution, length: { maximum: 255 }
	validates :note, length: { maximum: 255 }
	validates :payment_method, presence: true

	before_save :update_issue_status

	def self.get_query(query_param)
		case query_param
		when "unpaid"
			{ payment_status: 0 }
		when "unfulfilled"
			{ fulfillment_status: 0 }
		when "fulfilled"
			{ fulfillment_status: 1 }
		when "complained"
			{ issue_status: 1 }
		when "resolved"
			{ issue_status: 2 }
		end
	end

	def create_time
		self.created_at.utc.in_time_zone("Eastern Time (US & Canada)").strftime("%B %e, %Y (%A)")
	end	

	def create_time_to_min
		self.created_at.utc.in_time_zone("Eastern Time (US & Canada)").strftime("%H : %M, %B %e, %Y (%A)")
	end

	def delivery_time_to_min
		self.delivery_time.in_time_zone("Eastern Time (US & Canada)").strftime("%H : %M, %B %e, %Y (%A)")
	end

	def item_count
		self.orderables.count
	end

	private

		def update_issue_status
			feedback_created! if no_feedback? && !(issue.nil? || issue.empty?)
		end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController #this controller uses current_user. routes are not nested under shopper resource
	include ShopperValidations #contains valid_user
	before_action :logged_in_user
	before_action :valid_shopper, only: [:new, :create]
	before_action :valid_cart, only: [:new, :create]
	before_action :order_generation_router, only: [:new, :create]

	before_action :valid_order, only: [:show, :update]
	before_action :valid_shopper_or_admin, only: [:index]

	after_action :verify_authorized, only: [:show, :update]

	def index
		if @owner.is_a? Admin
			@num_unpaid = Order.where(Order.get_query("unpaid")).count
			@num_unfulfilled = Order.where(Order.get_query("unfulfilled")).count
			@num_fulfilled = Order.where(Order.get_query("fulfilled")).count
			@num_problem = Order.where(Order.get_query("complained")).count
			@num_feedback = Order.where(Order.get_query("resolved")).count

			@orders = Order.where(Order.get_query(params[:query])).order(created_at: :desc)
			render('orders/index/admin') 
		else
			@orders = @owner.orders.order(created_at: :desc)
			render('orders/index/user')
		end
	end

	def new
		case @instruction
		when "pickup_location needed"
			@template = 'orders/checkout_templates/location_info'
		when "locations_time needed"
			@template = 'orders/checkout_templates/time_info'
		when "recipient info needed"
			@order = Order.new(recipient_name: @shopper.name, recipient_phone: @shopper.phone, recipient_wechat: @shopper.wechat)
			@template = 'orders/checkout_templates/recipient_info'
		end
	end

	def create
		case @instruction
		when "ready to place order"
			order_generator = OrderGenerator.new(order_create_params, @locations_time, params[:stripeToken], @shopper)
			if order_generator.place_order
				@order = order_generator.order
				redirect_to order_url(@order)
			else
				@template = "orders/checkout_templates/recipient_info"
				flash.now[:error] = order_generator.payment_error if order_generator.cause_of_failure == "payment failure"
				@order = order_generator.order
				render "new"
			end
		when "locations_time posted"
			redirect_to new_locations_time_order_url(@locations_time)
		when "pickup_location posted"
			redirect_to new_pickup_location_order_url(@pickup_location)
		end
	end

	def show 
		authorize @order
	end 

	def update
		authorize @order		
		@order.assign_attributes( order_update_params ) if params[:order]
		@order.issue = params[:order][:issue] if @order.no_feedback? && current_user.shopper?
		raise Exceptions::InvalidOrderAttrsError unless @order.valid?
		@order.feedback_resolved! if params[:solved] == "1"
	rescue Exceptions::InvalidOrderAttrsError
		#this only works for user who provides lengthy input; not admin!
		flash.now[:error] = "Error! Please limit your input to under 255 characters"
		render 'show'
	rescue ArgumentError
		flash.now[:error] = "Error saving your satisfaction rating, please try again"
		render 'show'
	else
		@order.save
		admin_route = admin_orders_url(current_user.role, query: params[:query])
		shopper_route = request.referrer || order_url(@order)
		msg = "Updated successfully"
		redirect_and_flash( (current_user.admin? ? admin_route : shopper_route), :success, msg)
	end

	private
		
		def valid_shopper
			redirect_and_flash(menu_url, :error, "Access denied") unless current_user.shopper?
			@shopper = current_user.role
		end

		def valid_shopper_or_admin
			@owner = params[:shopper_id] ? Shopper.find(params[:shopper_id]) : Admin.find(params[:admin_id])
			redirect_and_flash(menu_url, :error, "Unauthorized access") unless (current_user.role == @owner || current_user.admin?) 
		rescue ActiveRecord::RecordNotFound
			redirect_and_flash(menu_url, :error, "Access denied")
		end

		def order_generation_router
			if params[:order]
				@instruction = "ready to place order"
				@locations_time = LocationsTime.find(params[:locations_time_id])
				raise Exceptions::InactiveDeliveryLocationError unless @locations_time.pickup_location.active?
			elsif params[:locations_time_id]
				@instruction = request.get? ? "recipient info needed" : "locations_time posted"
				@locations_time = LocationsTime.find(params[:locations_time_id])
				raise Exceptions::InactiveDeliveryLocationError unless @locations_time.pickup_location.active?
			elsif params[:pickup_location_id]
				@instruction = request.get? ? "locations_time needed" : "pickup_location posted"
				@pickup_location = PickupLocation.find(params[:pickup_location_id])
				raise Exceptions::InactiveDeliveryLocationError unless @pickup_location.active?
			else
				@instruction = "pickup_location needed"
			end	
		rescue ActiveRecord::RecordNotFound
			redirect_and_flash(shopper_checkout_url(@shopper), :error, "Invalid delivery location or time")
		rescue Exceptions::InactiveDeliveryLocationError
			redirect_and_flash(shopper_checkout_url(@shopper), :error, "Inactive delivery location")
		end

		def valid_cart
			if @shopper.item_count == 0
				redirect_and_flash(menu_url, :error, "Your cart is empty. Please add items before checkout.")
			elsif @shopper.invalid_orderables?
				redirect_and_flash(shopper_cart_url(@shopper), :error, "Please remove unavailable or verify changed items before checkout")
			end
		end

 		def valid_order
			@order = Order.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			redirect_and_flash(shopper_orders_url(current_user.role), :error, "Invalid request")
 		end

 		def order_update_params
 			params[:order][:satisfaction] = params[:order][:satisfaction].to_i if params[:order][:satisfaction]
 			params.require(:order).permit(policy(@order).permitted_update_attributes)
 		end

		def order_create_params
			params.require(:order).permit(policy(Order).permitted_create_attributes)
		end

end

app/views/orders/checkout_templates/_location_info.html.erb
<div class="row">
	<div class="center aligned column">
		<div class="ui steps">
		  <div class="active step">
		    <i class="truck icon"></i>
		    <div class="content">
		      <div class="title">Shipping</div>
		      <div class="description">Choose your delivery location</div>
		    </div>
		  </div>

		  <div class="disabled step">
		    <i class="wait icon"></i>
		    <div class="content">
		      <div class="title">Timing</div>
		      <div class="description">Select delivery time</div>
		    </div>
		  </div>

		  <div class="disabled step">
		    <i class="info icon"></i>
		    <div class="content">
		      <div class="title">Recipient</div>
		      <div class="description">Enter recipient information</div>
		    </div>
		  </div>
		</div>
	</div>
</div>

<div class="row">
	<%= form_tag shopper_orders_url(@shopper), class: "ui form column" do %>
		<div class="field">
			<%= label_tag :pickup_location_id, "Delivery Location" %>
			<%= select_tag(:pickup_location_id, options_from_collection_for_select(PickupLocation.where(active: true), :id, :name), { include_blank: "Select delivery location", class: "ui fluid dropdown" }) %>
		</div>
		<div class="field">
			<%= submit_tag "Continue", class: "ui blue inverted button" %>
		</div>
	<% end %>
</div>

app/views/orders/checkout_templates/_recipient_info.html.erb
<div class="row">
	<div class="center aligned column">
		<div class="ui steps">
		  <div class="step">
		    <i class="truck icon"></i>
		    <div class="content">
		      <div class="title"><%= link_to "Shipping", shopper_checkout_url(@shopper), class: "linkNoColor" %></div>
		      <div class="description">Choose your delivery location</div>
		    </div>
		  </div>

		  <div class="step">
		    <i class="wait icon"></i>
		    <div class="content">
		      <div class="title"><%= link_to "Timing", new_pickup_location_order_url(@locations_time.pickup_location), class: "linkNoColor" %></div>
		      <div class="description">Select delivery time</div>
		    </div>
		  </div>

		  <div class="active step">
		    <i class="info icon"></i>
		    <div class="content">
		      <div class="title">Recipient</div>
		      <div class="description">Enter recipient information</div>
		    </div>
		  </div>
		</div>
	</div>
</div>

<div class="row">
	<%= form_for @order, url: locations_time_orders_url(@locations_time) , html: { class: ["ui", "form", "column"], id: "placeOrderForm" } do |f| %>
		<%= render 'shared/error_msgs', object: f.object %>
		<div class="ui container grid">
			<div class="two column row">
				<div class="column">
					<div class="field">
						<%= f.label :recipient_name, "Who's picking up? (required)" %>
						<%= icon_input_wrapper(f, :recipient_name, :spy) %>
					</div>
				</div>
				<div class="column">
					<div class="field">
						<%= f.label :recipient_phone, "Contact number? (required)" %>
						<%= icon_input_wrapper(f, :recipient_phone, :call) %>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="field column">
					<%= f.label :recipient_wechat, "Contact by WeChat? (optional)" %>
					<%= icon_input_wrapper(f, :recipient_wechat, :wechat) %>
				</div>
			</div>

			<div class="row">
				<h4 class="ui horizontal divider header" class="locationEditTopDivider">
				  <i class="dollar icon"></i>
				  Payment Information
				</h4>
			</div>
			<div class="row">
				<div class="field column">
					<%= f.label :payment_method do %>
						Payment Method:
						<%= semantic_icon "inverted blue visa" %>
						<%= semantic_icon "inverted blue mastercard" %>
						<%= semantic_icon "inverted blue american express" %>
						<%= semantic_icon "inverted blue discover" %>
					<% end %>
					<%= f.select(:payment_method, [['Pay Online', 'online'], ['Pay Cash', 'cash']], { include_blank: "select payment method"}, { class: "ui fluid dropdown", id: ""}) %>
					<small>Teamond handles all online transactions through secure payment service provider, Stripe <%= semantic_icon "stripe inverted blue" %>, a PCI Certified Level 1 provider. We do NOT process NOR store your payment information.</small>
				</div>
			</div>


			<div class="row" id="stripePaymentButton">
			  <script
			    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
			    data-key="pk_test_tGb2jwze3GQ52hrSyUKXSu58"
			    data-image="https://stripe.com/img/open-graph/logo.png?2"
			    data-name="Teamond"
			    data-description="secure checkout"
			    data-amount="<%= @shopper.cart_balance_after_tax_in_penny %>"
			    data-locale="auto"
			    data-email="<%= @shopper.email %>">
			  </script>
			</div>

			<div class="row" id="placeOrderButton">
				<div class="column">
				 	<%= f.submit "Place Order", class: "ui blue inverted button" %>
			 	</div>
			</div>

			<div class="row" id="payOnlineButton">
				<div class="column">
				 	<%= f.submit "Place Order", class: "ui blue inverted button" %>
			 	</div>
			</div>

		</div>
	<% end %>
</div>

app/views/orders/checkout_templates/_summary.html.erb
<div class="row">
	<div class="ui breadcrumb">
	  <%= link_to "Shopping Cart", shopper_checkout_url(@shopper), class: "section" %>
	  <i class="right angle icon divider"></i>
	  <div class="active section">Order Summery</div>
	</div>
</div>

<div class="row">
	<h4 class="ui horizontal divider header" class="locationEditTopDivider">
	  <i class="calculator icon"></i>
	  Order Summary
	</h4>
</div>

<div class="row">
	<div class="ui cards">
		<% @shopper.orderables.each do |orderable| %>
			<%= render 'orders/cards/item_card_checkout', orderable: orderable %>
		<% end %>
	</div>
</div>

<div class="centered row" id="paymentSummary">
	<div class="ui fluid card" id="checkoutPriceSummary">
		<div class="content">
			<p>Total before Tax: $ <%= @shopper.cart_balance_before_tax %></p>
			<p>Sales Tax (8%): $ <%= @shopper.cart_balance_tax %></p> 
		</div>
		<div class="extra content">
			<p>Total Payment: $ <%= @shopper.cart_balance_after_tax %></p>
		</div>
	</div>
</div>

app/views/orders/checkout_templates/_time_info.html.erb
<div class="row">
	<div class="center aligned column">
		<div class="ui steps">
		  <div class="step">
		    <i class="truck icon"></i>
		    <div class="content">
		      <div class="title"><%= link_to "Shipping", shopper_checkout_url(@shopper), class: "linkNoColor" %></div>
		      <div class="description">Choose your delivery location</div>
		    </div>
		  </div>

		  <div class="active step">
		    <i class="wait icon"></i>
		    <div class="content">
		      <div class="title">Timing</div>
		      <div class="description">Select delivery time</div>
		    </div>
		  </div>

		  <div class="disabled step">
		    <i class="info icon"></i>
		    <div class="content">
		      <div class="title">Recipient</div>
		      <div class="description">Enter recipient information</div>
		    </div>
		  </div>
		</div>
	</div>
</div>

<div class="row">
	<%= form_tag pickup_location_orders_url(@pickup_location), class: "ui form column" do %>
		<div class="field">
			<%= label_tag :locations_time_id, "Delivery Time" %>
			<%= select_tag(:locations_time_id, options_from_collection_for_select(@pickup_location.valid_associations, :id, :associated_pickup_time), { include_blank: "Select delivery time", class: "ui fluid dropdown" }) %>
			<small>Didn't find the time you like? Check out our delivery schedule and see delivery times for other locations!</small>
		</div>
		<div class="field">
			<%= submit_tag "Continue", class: "ui blue inverted button" %>
		</div>
	<% end %>
</div>